In [1]:
# imports
import pickle
import pulp
from pulp import *
import re
import pandas as pd
import numpy as np
import itertools
import pickle
import matplotlib.pyplot as plt

In [2]:
# read in the data
DATE = '2019-12-01'

file = open("consolidated_many_days.pkl",'rb')
file2 = open("consolidated_many_days2.pkl",'rb')
data = pickle.load(file)
data2 = pickle.load(file2)
data.update(data2)


example_contest = data[DATE]['CONTESTS'][0]['PAYOUTS']
example_results = data[DATE]['ACTUAL_POINTS']
example_projections = data[DATE]['PROJECTIONS']

COST = data[DATE]['CONTESTS'][0]['Buy In']
example_results

#example_results

FileNotFoundError: [Errno 2] No such file or directory: 'consolidated_many_days.pkl'

In [ ]:
data.keys()

In [ ]:
# process the data
#trasform the columns so the names agree with each other
def process_name(name):
    filtered = re.sub(r'([^\s\w]|_)+', '', name)
    #dumb edge cases
    if filtered == 'Moe Harkless':
        filtered = 'Maurice Harkless'
    if filtered == 'Wes Iwundu':
        filtered = 'Wesley Iwundu'
    if filtered == 'Juan Hernangomez':
        filtered = 'Juancho Hernangomez'
    return filtered.split()[0]+ " " + filtered.split()[1]
def get_Fpts(df, player):
    df = df[df['Player'] == player]
    #print(df)
    #print(player)
    try:
        return 0 if np.isnan(df.iloc[0].Fpts) else df.iloc[0].Fpts
    except:
        #print("???")
        return 0
example_projections = dict((process_name(key), value) for (key, value) in example_projections.items())
example_results.Player = example_results.Player.apply(lambda x: process_name(x))

In [ ]:
players = set()
for date in data:
    players.update(set(data[date]['ACTUAL_POINTS'].Player))
for player in players:
    player = process_name(player)

In [3]:
players

NameError: name 'players' is not defined

In [ ]:
name = 'JaMychal Green'
residuals = []
for date in data:
    if name in data[date]['PROJECTIONS'] and name in set(data[date]['ACTUAL_POINTS'].Player):
        residuals.append(get_Fpts(data[date]['ACTUAL_POINTS'],name)-data[date]['PROJECTIONS'][name]['points'])

In [4]:
plt.hist(residuals)

NameError: name 'residuals' is not defined

In [5]:
sum(residuals)/len(residuals)

NameError: name 'residuals' is not defined

In [6]:
np.std(residuals)

NameError: name 'residuals' is not defined

In [7]:
10*(8**.5)

28.284271247461902

In [8]:

for name in players:
    residuals = []
    acts = []
    for date in data:
        if name in data[date]['PROJECTIONS'] and name in set(data[date]['ACTUAL_POINTS'].Player):
            acts.append(get_Fpts(data[date]['ACTUAL_POINTS'],name))
            residuals.append(get_Fpts(data[date]['ACTUAL_POINTS'],name)-data[date]['PROJECTIONS'][name]['points'])
    if len(residuals) != 0:
        print(np.std(residuals),np.mean(acts) )

NameError: name 'players' is not defined

In [9]:
13.5*(8**.5)

38.18376618407357

In [10]:
from scipy import stats
name1 = "LeBron James"
name2 = "Anthony Davis"
#name1 = "J.J. Redick"
#name2 = "LeBron James"
for name2 in players:
    X = []
    Y = []
    #print(name1)
    for date in data:
        #print(date)
        projs = data[date]['PROJECTIONS']
        trues = set(data[date]['ACTUAL_POINTS'].Player)
        if name1 in projs and name2 in projs and name1 in trues and name2 in trues:
            #print("hello")
            X.append(get_Fpts(data[date]['ACTUAL_POINTS'],name1)-data[date]['PROJECTIONS'][name1]['points'])
            Y.append(get_Fpts(data[date]['ACTUAL_POINTS'],name2)-data[date]['PROJECTIONS'][name2]['points'])
    if len(X) > 20:
        slope, intercept, r_value, p_value, std_err = stats.linregress(X,Y)
        print(name2, np.corrcoef(X,Y)[0][1], p_value)


#X



NameError: name 'players' is not defined

In [ ]:
for name2 in ["Jordan Clarkson"]:
    X = []
    Y = []
    #print(name1)
    for date in data:
        #print(date)
        projs = data[date]['PROJECTIONS']
        trues = set(data[date]['ACTUAL_POINTS'].Player)
        if name1 in projs and name2 in projs and name1 in trues and name2 in trues:
            #print("hello")
            X.append(get_Fpts(data[date]['ACTUAL_POINTS'],name1)-data[date]['PROJECTIONS'][name1]['points'])
            Y.append(get_Fpts(data[date]['ACTUAL_POINTS'],name2)-data[date]['PROJECTIONS'][name2]['points'])
    if len(X) > 10:
        print(name2, np.corrcoef(X,Y)[0][1])

In [ ]:
plt.scatter(X,Y)

In [ ]:
X

In [11]:
Y

NameError: name 'Y' is not defined

In [12]:
example_projections

NameError: name 'example_projections' is not defined

In [13]:
from scipy.linalg import cholesky

# Correlation matrix
corr_mat= np.array([[1, .25, .25, 0, 0, 0, 0, 0,],
                    [.25, 1, .25, 0, 0, 0, 0, 0,],
                    [.25, .25, 1, 0, 0, 0, 0, 0,],
                    [0, 0, 0, 1, .25, .25,0, 0,],
                    [0, 0, 0, .25, 1, .25,0, 0,],
                    [0, 0, 0, .25, .25, 1,0, 0,],
                    [0, 0, 0, 0, 0, 0,1, .25,],
                    [0, 0, 0, 0, 0, 0,.25, 1,],])
"""
corr_mat= np.array([[1, -.4, -.4,],
                    [-.4, 1, -.4],
                    [-.4, -.4, 1],])
"""
# Compute the (upper) Cholesky decomposition matrix
upper_chol = cholesky(corr_mat)

# Generate 3 series of normally distributed (Gaussian) numbers
rnd = np.random.normal(30, 13, size=(10**7, 8))

# Finally, compute the inner product of upper_chol and rnd
ans = rnd @ upper_chol

In [14]:
ans

array([[45.38592415, 56.46443295, 75.28330523, ..., 31.36871247,
        46.98263551, 34.87310826],
       [45.71201495, 42.89199468, 49.67373037, ..., 47.51110059,
        34.62195047, 38.29468035],
       [27.28413723, 38.0596632 , 50.61842296, ..., 16.57171021,
        21.04971909, 56.57853505],
       ...,
       [27.26778239, 44.53074722, 60.73475284, ..., 49.95679422,
        22.56942586, 49.34257572],
       [19.92822221, 29.13497391, 41.54516762, ..., 35.61998002,
        28.16545545, 28.72012374],
       [25.28489744, 25.5702256 , 42.45151675, ..., 44.69617881,
        24.11267478, 49.2357196 ]])

In [15]:
rnd

array([[45.38592415, 46.59762036, 57.88363085, ..., 23.34786446,
        46.98263551, 23.88592702],
       [45.71201495, 32.49587011, 33.68134393, ..., 30.30925578,
        34.62195047, 30.61122662],
       [27.28413723, 32.26311719, 39.58082001, ...,  4.66434803,
        21.04971909, 52.99904564],
       ...,
       [27.26778239, 38.95064683, 48.88359162, ..., 33.22999797,
        22.56942586, 45.13339238],
       [19.92822221, 24.94502682, 33.44902189, ..., 25.83717117,
        28.16545545, 22.38972692],
       [25.28489744, 19.88028299, 34.02662639, ..., 33.10709146,
        24.11267478, 44.62456669]])

In [23]:
len(ans)

10000000

In [24]:
np.std(ans.T[0])

13.00038574227799

In [25]:
np.std(np.sum(ans, axis=1))

44.0849677618824

In [26]:
10*8**.5

28.284271247461902

In [27]:
upper_chol

array([[1.        , 0.25      , 0.25      , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.96824584, 0.19364917, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.9486833 , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.25      ,
        0.25      , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.96824584,
        0.19364917, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.9486833 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.25      ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.96824584]])

In [28]:
13*8**.5

36.76955262170048

In [1]:
data.key()

NameError: name 'data' is not defined